### ISSUE TITLE
Decorating class methods defined within a module

### ISSUE THREAD

**Issue by tubbo** [workarea-commerce/rails-decorators#4]
Given the following base code:

```ruby
module Hammer
  def self.cant_touch_this!
    "what's the time? hammer #{Time.now}".
  end
end
```

and my decorator:

```ruby
decorate Hammer do
  class_methods do
    def cant_touch_this!
      "what's the time? hammer time"
    end
  end
end
```

I get an error indicating that the `Hammer` module cannot be decorated, but the reasoning behind preventing me from doing this seems like it doesn't apply to my use case. Class methods should always be safe to decorate, and the error is only applicable when you try to define instance methods as a part of your decorator.

**Comment by bencrouse** [comment]
Technically you're right. The difficulty I see is in allowing this while still enforcing/warning the developer that if they try to add instance methods you're gonna have a bad time. It also creates an awkward documentation situation where we have to communicate that while you can't decorate modules in the full way that you can with classes, there is this one capability.

I think a step back to ask the deeper question of "are there ways we could allow full module decoration" would lead down a better path. Something like `decorate_module` or whatever that we could use a totally different style of implementation to achieve the goals.

**Comment by mrkplt** [comment]
I like `decorate_module` since it could be documented with specific caveats on it's use.

One thing that should  be considered is detecting when a decorated module is mixed into a class and displaying a warning to the developer that the behavior may not work as expected. I might go so far as to make that cause the application to abort on start.

**Comment by tubbo** [comment]
Closing this in favor of #9, since it solves this use case as well as others.
